/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Operaciones.OperacionesAsiento;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Ajustes extends javax.swing.JFrame {

    double saldo = 0, deber = 0, haber = 0;
    String valor = "";
    OperacionesAsiento op = new OperacionesAsiento();
    indexHome tito = new indexHome();

    /**
     * Creates new form Asientos
     */
    public Ajustes() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/wrench_orange.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLsaldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAsiento = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jbNuevoLimpiar = new javax.swing.JButton();
        txtNumeroAsiento = new javax.swing.JTextField();
        dcFecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroCuenta = new javax.swing.JTextField();
        jcTipoAbono = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        btnAgregarMovimiento = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnSeleccionarCuenta = new javax.swing.JButton();
        btnEliminarMovimiento = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCuentas = new javax.swing.JTable();
        btnSeleccionarCuentaCuadro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnEjecutarCambios = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtLibroDiario = new javax.swing.JTable();
        guardarexcel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        btnLlevarLibroDiario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tabla de Ajustes");
        setMinimumSize(new java.awt.Dimension(880, 501));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(890, 594));
        setResizable(false);

        jLsaldo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLsaldo.setText("0");

        jTAsiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# Asiento", "fecha", "N° Cuenta", "D/H", "Importe", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(jTAsiento);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Diferencia:");

        jbNuevoLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new.png"))); // NOI18N
        jbNuevoLimpiar.setText("Limpiar");
        jbNuevoLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoLimpiarActionPerformed(evt);
            }
        });

        txtNumeroAsiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroAsientoKeyTyped(evt);
            }
        });

        dcFecha.setDateFormatString("dd-MM-yyyy");

        jLabel2.setText("Fecha:");

        jLabel1.setText("Ajuste #:");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("N° Cuenta:");

        txtNumeroCuenta.setEditable(false);
        txtNumeroCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroCuentaKeyTyped(evt);
            }
        });

        jcTipoAbono.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Deber", "Haber" }));

        jLabel8.setText("Tipo de Abono:");

        jLabel4.setText("Importe:");

        txtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImporteKeyTyped(evt);
            }
        });

        btnAgregarMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnAgregarMovimiento.setText("Agregar Ajuste");
        btnAgregarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMovimientoActionPerformed(evt);
            }
        });

        jLabel5.setText("Descripcion:");

        btnSeleccionarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_open.png"))); // NOI18N
        btnSeleccionarCuenta.setText("Seleccionar Cuenta");
        btnSeleccionarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarCuentaActionPerformed(evt);
            }
        });

        btnEliminarMovimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnEliminarMovimiento.setText("Eliminar Ajuste");
        btnEliminarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMovimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAgregarMovimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarMovimiento))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSeleccionarCuenta)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcTipoAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jcTipoAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarMovimiento)
                    .addComponent(btnEliminarMovimiento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("No se Guardaaaaaaaaa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumeroAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbNuevoLimpiar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNumeroAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel11))
                    .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLsaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNuevoLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ajuste", jPanel1);

        jtCuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtCuentas);

        btnSeleccionarCuentaCuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        btnSeleccionarCuentaCuadro.setText("Seleccionar Cuenta");
        btnSeleccionarCuentaCuadro.setEnabled(false);
        btnSeleccionarCuentaCuadro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarCuentaCuadroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSeleccionarCuentaCuadro)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionarCuentaCuadro)
                .addGap(157, 157, 157))
        );

        jTabbedPane1.addTab("Lista de Cuentas", jPanel3);

        btnEjecutarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accept.png"))); // NOI18N
        btnEjecutarCambios.setText("Ejecutar Ajustes en el Sistema");
        btnEjecutarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarCambiosActionPerformed(evt);
            }
        });

        jtLibroDiario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# Asiento", "Fecha", "Cuenta", "D/H", "Importe", "Descripción"
            }
        ));
        jScrollPane3.setViewportView(jtLibroDiario);

        guardarexcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/page_white_excel.png"))); // NOI18N
        guardarexcel.setText("Guardar en tabla de Excel");
        guardarexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarexcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEjecutarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEjecutarCambios)
                    .addComponent(guardarexcel))
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Tabla de Ajustes a realizar", jPanel2);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ajustes de: ");

        jlNombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNombreEmpresa.setText("getNombreEmpresa()");

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        btnLlevarLibroDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/layout_add.png"))); // NOI18N
        btnLlevarLibroDiario.setText("Llevar a Tabla de Ajustes a realizar");
        btnLlevarLibroDiario.setEnabled(false);
        btnLlevarLibroDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlevarLibroDiarioActionPerformed(evt);
            }
        });

        idCatalogo.setForeground(new java.awt.Color(240, 240, 240));

        tipoUsuario.setForeground(new java.awt.Color(240, 240, 240));
        tipoUsuario.setText("tipoUsuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlNombreEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipoUsuario)
                        .addGap(46, 46, 46)
                        .addComponent(idCatalogo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLlevarLibroDiario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlNombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipoUsuario))
                    .addComponent(idCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLlevarLibroDiario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(880, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMovimientoActionPerformed
        // TODO add your handling code here:

        if (txtNumeroCuenta.getText().trim().isEmpty()
                || txtImporte.getText().trim().isEmpty()
                || txtDescripcion.getText().trim().isEmpty()
                || txtNumeroAsiento.getText().trim().isEmpty()
                || dcFecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "No ha ingresado todos los valores", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {

            DefaultTableModel modelo = (DefaultTableModel) jTAsiento.getModel();

            Object[] fila = new Object[6];

            SimpleDateFormat fechaPersonalizada = new SimpleDateFormat("dd - MM - yyyy");
            String fecha = fechaPersonalizada.format(dcFecha.getDate());

            fila[0] = txtNumeroAsiento.getText();
            fila[1] = fecha;
            fila[2] = txtNumeroCuenta.getText();
            fila[3] = jcTipoAbono.getSelectedItem();
            fila[4] = txtImporte.getText();
            fila[5] = txtDescripcion.getText();

            String tipo = "Deber";

            if (tipo.equals(jcTipoAbono.getSelectedItem())) {
                deber = deber + Double.parseDouble(txtImporte.getText());
            } else {
                haber = haber + Double.parseDouble(txtImporte.getText());
            }

            modelo.addRow(fila);

            jTAsiento.setModel(modelo);//agregamo… el modelo de tabla al jTable

            saldo = deber - haber;
            valor = String.valueOf(saldo);
            jLsaldo.setText("$" + valor);
            valor = "";
            txtNumeroAsiento.setText("");

            limpiarBasura();
            verificarAsientos();
        }


    }//GEN-LAST:event_btnAgregarMovimientoActionPerformed

    private void btnLlevarLibroDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlevarLibroDiarioActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTAsiento.getModel();
        DefaultTableModel modelito = (DefaultTableModel) jtLibroDiario.getModel();
        Object[] fila = new Object[6];

        for (int i = 0; i < modelo.getRowCount(); i++) {

            fila[0] = (String) modelo.getValueAt(i, 0);
            fila[1] = (String) modelo.getValueAt(i, 1);
            fila[2] = (String) modelo.getValueAt(i, 2);
            fila[3] = (String) modelo.getValueAt(i, 3);
            fila[4] = (String) modelo.getValueAt(i, 4);
            fila[5] = (String) modelo.getValueAt(i, 5);
            modelito.addRow(fila);
            System.out.print("exito");
        }

        jTabbedPane1.setSelectedIndex(2);
        jTabbedPane1.setEnabledAt(0, false);
    }//GEN-LAST:event_btnLlevarLibroDiarioActionPerformed

    private void btnSeleccionarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarCuentaActionPerformed
        // Seleccionar Cuentas:

        btnSeleccionarCuentaCuadro.setEnabled(true);
        jTabbedPane1.setSelectedIndex(1);

    }//GEN-LAST:event_btnSeleccionarCuentaActionPerformed

    private void jbNuevoLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoLimpiarActionPerformed
        // Limpiar todo
        limpiarBasura();

    }//GEN-LAST:event_jbNuevoLimpiarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // Salirr!!!:::
        salir();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void txtNumeroCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroCuentaKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroCuentaKeyTyped

    private void txtImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtImporteKeyTyped

    private void txtNumeroAsientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroAsientoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroAsientoKeyTyped

    private void btnSeleccionarCuentaCuadroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarCuentaCuadroActionPerformed
        // TODO add your handling code here:
        int fila = jtCuentas.getSelectedRow();

        txtNumeroCuenta.setText(jtCuentas.getValueAt(fila, 0).toString());

        btnSeleccionarCuentaCuadro.setEnabled(false);
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_btnSeleccionarCuentaCuadroActionPerformed

    private void btnEliminarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMovimientoActionPerformed
        // TODO add your handling code here:

        DefaultTableModel modelo = (DefaultTableModel) jTAsiento.getModel();

        int fila = jTAsiento.getSelectedRow();

        if (fila >= 0) {

            if (jTAsiento.getValueAt(fila, 1).equals("Deber")) {

                deber = deber - Double.parseDouble(jTAsiento.getValueAt(fila, 2).toString());

                saldo = saldo - Double.parseDouble(jTAsiento.getValueAt(fila, 2).toString());
                valor = String.valueOf(saldo);
                jLsaldo.setText("$" + valor);
                valor = "";
                verificarAsientos();

//                System.out.println("Al eliminar saldo = " + saldo);
//                System.out.println("Al eliminar haber = " + haber);
//                System.out.println("Al eliminar deber = " + deber);

            } else {

                haber = haber - Double.parseDouble(jTAsiento.getValueAt(fila, 2).toString());

                saldo = saldo + Double.parseDouble(jTAsiento.getValueAt(fila, 2).toString());
                valor = String.valueOf(saldo);
                jLsaldo.setText("$" + valor);
                valor = "";
                verificarAsientos();
//                System.out.println("Al eliminar saldo = " + saldo);
//                System.out.println("Al eliminar haber = " + haber);
//                System.out.println("Al eliminar deber = " + deber);
            }

            modelo.removeRow(fila);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione movimiento a Eliminar", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnEliminarMovimientoActionPerformed

    private void guardarexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarexcelActionPerformed
        // TODO add your handling code here:
        accionGuardar();
    }//GEN-LAST:event_guardarexcelActionPerformed

    private void btnEjecutarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarCambiosActionPerformed
        // Realizar los cambios en la base de datos...

        if (JOptionPane.showConfirmDialog(null, "¿Ha confirmado que los cambios a realizar son correctos?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            DefaultTableModel modelo = (DefaultTableModel) jtLibroDiario.getModel();
            int id_catalogo = 0;

            for (int x = 0; x < modelo.getRowCount(); x++) {
                String numcuenta = (String) jtLibroDiario.getValueAt(x, 2);
                String tipo = (String) jtLibroDiario.getValueAt(x, 3);
                String monto = (String) jtLibroDiario.getValueAt(x, 4);
                int id = Integer.parseInt(numcuenta);
                id_catalogo = Integer.parseInt(idCatalogo.getText());
                double importe = Double.parseDouble(monto);

                if (tipo.equals("Deber")) {
                    op.asientosuma(id, id_catalogo, importe);
                } else {
                    op.asientoresta(id, id_catalogo, importe);
                }
            }
            op.actualizarDatos(id_catalogo);
            salir();
            JOptionPane.showMessageDialog(null, "Asientos Diarios Realizados con éxito.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEjecutarCambiosActionPerformed

    public void salir() {
        if (this.tipoUsuario.getText().trim() == "1") {
            indexHome boladito = new indexHome();
            boladito.setVisible(true);
            boladito.jmLibroDiario.setVisible(false);
            boladito.jmCierres.setVisible(false);
            boladito.jmAsientos.setVisible(false);
            boladito.jlLogueadoComo.setText("Logueado como Usuario sin credencial");
            this.hide();
            System.out.println("WUUJUUU!!!");
        } else {
            new indexHome().setVisible(true);
            indexHome.jlLogueadoComo.setText("Logueado como Administrador");
            this.hide();
        }
    }

    public void limpiarBasura() {
        txtNumeroCuenta.setText("");
        txtImporte.setText("");
        txtDescripcion.setText("");
        txtNumeroCuenta.setText("");
    }

    public void accionGuardar() {
        JFileChooser abrir = new JFileChooser();
        abrir.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado = abrir.showSaveDialog(this);
        if (resultado == JFileChooser.CANCEL_OPTION) {
            return;
        }
        File archivo = abrir.getSelectedFile();
        try {//".csv"
            PrintWriter salida = new PrintWriter(new FileWriter(archivo + ".csv"));
            String data[][] = obtenerInformacion();
            for (int i = 0; i < data.length; i++) {
                salida.print(data[i][0]);
                for (int j = 1; j < data[i].length; j++) {
                    String work = data[i][j];
                    if (work != null) {
                        salida.print("," + work);
                    } else {
                        salida.print(",");
                    }
                }
                salida.println();
            }
            salida.close();
        } catch (Exception e) {
        }
    }

    public String[][] obtenerInformacion() {
        DefaultTableModel modelo3 = (DefaultTableModel) jtLibroDiario.getModel();
        int numFilas = modelo3.getRowCount();
        int numColumnas = modelo3.getColumnCount();
        boolean isCapturedTheTitles = false;
        String Matriz[][] = new String[numFilas + 1][numColumnas];
        for (int i = 0; i < numFilas; i++) {
            for (int x = 0; x < numColumnas; x++) {

                if (!isCapturedTheTitles) {
                    Matriz[0][x] = modelo3.getColumnName(x);
                    isCapturedTheTitles = (i > 0) ? true : false;
                }
                Matriz[i + 1][x] = "" + modelo3.getValueAt(i, x);
            }
        }
        return Matriz;
    }

    public void listarCuentas() {
        op.listarCatalogo(jtCuentas, Integer.parseInt(this.idCatalogo.getText()));
    }

    public void verificarAsientos() {
        String valor = jLsaldo.getText();
        System.out.println(valor);
        if (valor.trim().equals("$0.0")) {
            btnLlevarLibroDiario.setEnabled(true);
        } else {
            btnLlevarLibroDiario.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajustes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMovimiento;
    private javax.swing.JButton btnEjecutarCambios;
    private javax.swing.JButton btnEliminarMovimiento;
    private javax.swing.JButton btnLlevarLibroDiario;
    private javax.swing.JButton btnSeleccionarCuenta;
    private javax.swing.JButton btnSeleccionarCuentaCuadro;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JButton guardarexcel;
    public static final javax.swing.JLabel idCatalogo = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLsaldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTAsiento;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbNuevoLimpiar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox jcTipoAbono;
    public static final javax.swing.JLabel jlNombreEmpresa = new javax.swing.JLabel();
    private javax.swing.JTable jtCuentas;
    private javax.swing.JTable jtLibroDiario;
    public static final javax.swing.JLabel tipoUsuario = new javax.swing.JLabel();
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtNumeroAsiento;
    private javax.swing.JTextField txtNumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
