/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

//import Operaciones.Operaciones;
import Operaciones.OperacionesEmpresa;
import Operaciones.OperacionesEstadosFinancieros;
import clases.Cuenta;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.math.*;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.PrinterName;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Tablo
 */
public class BalanceGeneral extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form BalanceGeneral
     */
    OperacionesEstadosFinancieros op = new OperacionesEstadosFinancieros();


    DecimalFormat df = new DecimalFormat("00.00");

    OperacionesEmpresa opModificar = new OperacionesEmpresa();

    public BalanceGeneral() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/coins.png")).getImage());
        jPinicioER.setVisible(false);
        lblMCodigo.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPEsDefecto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtIngresosEstadoResultado = new javax.swing.JTable();
        jlTotalIngresos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtGastosEstadoResultados = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlUtilidadEstadoResultado = new javax.swing.JLabel();
        lblUtilidadAV = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlTotalGastos = new javax.swing.JLabel();
        lblIngresosAV = new javax.swing.JLabel();
        lblGastosAV = new javax.swing.JLabel();
        jPinicioER = new javax.swing.JPanel();
        btnEsDefecto = new javax.swing.JButton();
        btnEsPersonalizado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtCapitalesEstadoResultado = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlUtilidad = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtRetiros = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jlTotalRetiros = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jlTotalCapital = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        jtActivosCorrientesBG = new javax.swing.JTable();
        jLabel53 = new javax.swing.JLabel();
        lblTotalActivosCorrientesBG = new javax.swing.JLabel();
        lblActivosCorrientesAV = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        jtPasivosCorrientesBG = new javax.swing.JTable();
        jLabel55 = new javax.swing.JLabel();
        lblTotalPasivosCorrientesBG = new javax.swing.JLabel();
        lblPasivosCorrientesAV = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        jtActivosFijosBG = new javax.swing.JTable();
        jLabel61 = new javax.swing.JLabel();
        lblTotalActivosFijosBG = new javax.swing.JLabel();
        lblActivosFijosAV = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        jtPasivosFijosBG = new javax.swing.JTable();
        jLabel63 = new javax.swing.JLabel();
        lblTotalPasivosFijosBG = new javax.swing.JLabel();
        lblPasivosFijosAV = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jScrollPane26 = new javax.swing.JScrollPane();
        jtCapitalContableBG = new javax.swing.JTable();
        jLabel65 = new javax.swing.JLabel();
        lblTotalCapitalBG = new javax.swing.JLabel();
        lblCapitalContableAV = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTotalActivosBG = new javax.swing.JLabel();
        lblTotalPasivosBG = new javax.swing.JLabel();
        lblActivosCorrientesAV1 = new javax.swing.JLabel();
        lblTotalActivosAV = new javax.swing.JLabel();
        lblTotalPasivosAV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPasivoCapital = new javax.swing.JLabel();
        lblPasivoCapitalAV = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTModificar = new javax.swing.JTable();
        lblMCodigo = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnMModificar = new javax.swing.JButton();
        btnMCancelar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtMSaldo = new javax.swing.JTextField();
        txtMIdPadre = new javax.swing.JTextField();
        txtMCuenta = new javax.swing.JTextField();
        cmbMTipo = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        Imprimir = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Estados Financieros");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(706, 689));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Estados Financieros de ");

        idCatalogo.setForeground(new java.awt.Color(240, 240, 240));

        jlNombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNombreEmpresa.setText("getNameEnterprise()");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPEsDefecto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtIngresosEstadoResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtIngresosEstadoResultado);

        jPEsDefecto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 207));

        jlTotalIngresos.setText("jlTotalIngresos");
        jPEsDefecto.add(jlTotalIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Ingresos Totales:");
        jPEsDefecto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Ingresos:");
        jPEsDefecto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Gastos Totales:");
        jPEsDefecto.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jtGastosEstadoResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtGastosEstadoResultados);

        jPEsDefecto.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 300, 207));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Utilidad Neta:");

        jlUtilidadEstadoResultado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlUtilidadEstadoResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlUtilidadEstadoResultado.setText("getValorUtilidad()");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlUtilidadEstadoResultado)
                .addGap(70, 70, 70)
                .addComponent(lblUtilidadAV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUtilidadEstadoResultado)
                    .addComponent(jLabel6)
                    .addComponent(lblUtilidadAV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPEsDefecto.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 525, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Gastos:");
        jPEsDefecto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jlTotalGastos.setText("jlTotalGastos");
        jPEsDefecto.add(jlTotalGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 260, 100, -1));
        jPEsDefecto.add(lblIngresosAV, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 50, 10));
        jPEsDefecto.add(lblGastosAV, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 50, 10));

        jPanel1.add(jPEsDefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 620, 490));

        jPinicioER.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEsDefecto.setText("Por Defecto");
        btnEsDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsDefectoActionPerformed(evt);
            }
        });
        jPinicioER.add(btnEsDefecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 181, 125, -1));

        btnEsPersonalizado.setText("Personalizado");
        jPinicioER.add(btnEsPersonalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 181, -1, -1));

        jPanel1.add(jPinicioER, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 380));

        jTabbedPane5.addTab("Estado de Resultado", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtCapitalesEstadoResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtCapitalesEstadoResultado);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Capital:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Utilidad:");

        jlUtilidad.setText("jlUtilidad");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jlUtilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlUtilidad))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Retiros:");

        jtRetiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtRetiros);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Total Retiros:");

        jlTotalRetiros.setText("jlTotalRetiros");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlTotalRetiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jlTotalRetiros))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlTotalCapital.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTotalCapital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTotalCapital.setText("jlTotalCapitalNuevo");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total Capital + Utilidad - Retiros:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                    .addComponent(jlTotalCapital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTotalCapital)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane5.addTab("Variación de Capital", jPanel2);

        jPanel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel52.setText("Activos corrientes:");

        jtActivosCorrientesBG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane20.setViewportView(jtActivosCorrientesBG);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel53.setText("Total activos corrientes: ");

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel52)
                            .addGroup(jPanel30Layout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalActivosCorrientesBG, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(lblActivosCorrientesAV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblActivosCorrientesAV))
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalActivosCorrientesBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel31.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel54.setText("Pasivos corrientes:");

        jtPasivosCorrientesBG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane21.setViewportView(jtPasivosCorrientesBG);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel55.setText("Total pasivos corrientes: ");

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addGroup(jPanel31Layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalPasivosCorrientesBG, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPasivosCorrientesAV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPasivosCorrientesAV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalPasivosCorrientesBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );

        jPanel34.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel60.setText("Activos fijos:");

        jtActivosFijosBG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane24.setViewportView(jtActivosFijosBG);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel61.setText("Total activos fijos: ");

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel34Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addComponent(jLabel61)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalActivosFijosBG, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblActivosFijosAV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblActivosFijosAV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel34Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel60)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalActivosFijosBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel35.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel62.setText("Pasivos fijos:");

        jtPasivosFijosBG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane25.setViewportView(jtPasivosFijosBG);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel63.setText("Total pasivos fijos: ");

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel62)
                            .addGroup(jPanel35Layout.createSequentialGroup()
                                .addComponent(jLabel63)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalPasivosFijosBG, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(lblPasivosFijosAV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35Layout.createSequentialGroup()
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPasivosFijosAV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel35Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel62)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalPasivosFijosBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel36.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel64.setText("Capital:");

        jtCapitalContableBG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane26.setViewportView(jtCapitalContableBG);

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel65.setText("Capital contable:");

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel36Layout.createSequentialGroup()
                        .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel64)
                            .addGroup(jPanel36Layout.createSequentialGroup()
                                .addComponent(jLabel65)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotalCapitalBG, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(lblCapitalContableAV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCapitalContableAV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalCapitalBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel14.setText("Total activos:");

        jLabel15.setText("Total pasivos:");

        jLabel2.setText("Total pasivos + Total capital:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalActivosBG, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(lblPasivoCapital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPasivoCapitalAV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalActivosAV, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                        .addGap(76, 76, 76)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalPasivosBG, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(lblTotalPasivosAV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(371, 371, 371)
                    .addComponent(lblActivosCorrientesAV1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(371, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                            .addComponent(lblTotalPasivosBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTotalPasivosAV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTotalActivosBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblTotalActivosAV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(lblPasivoCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPasivoCapitalAV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(303, 303, 303)
                    .addComponent(lblActivosCorrientesAV1)
                    .addContainerGap(318, Short.MAX_VALUE)))
        );

        jTabbedPane5.addTab("Balance General", jPanel3);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTModificar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTModificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Cuenta", "Saldo", "Deudor/Acrededor"
            }
        ));
        jTModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTModificarMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTModificar);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 450, -1));

        lblMCodigo.setText("codigo");
        jPanel10.add(lblMCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel18.setText("Cuenta");
        jPanel10.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMModificar.setText("Modificar");
        btnMModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMModificarActionPerformed(evt);
            }
        });
        jPanel8.add(btnMModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        btnMCancelar.setText("Cancelar");
        btnMCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCancelarActionPerformed(evt);
            }
        });
        jPanel8.add(btnMCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel19.setText("ID Padre");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel22.setText("Saldo");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 20));
        jPanel8.add(txtMSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, 30));
        jPanel8.add(txtMIdPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 120, 30));
        jPanel8.add(txtMCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 160, 30));

        cmbMTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deudor", "Acrededor" }));
        jPanel8.add(cmbMTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 160, 30));

        jPanel10.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 280, 330));

        jTabbedPane5.addTab("Modificar Cuentas", jPanel10);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tipoUsuario.setForeground(new java.awt.Color(240, 240, 240));
        tipoUsuario.setText("tipoUsuario");

        Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer.png"))); // NOI18N
        Imprimir.setText("Imprimir");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlNombreEmpresa))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoUsuario)
                .addGap(605, 605, 605)
                .addComponent(idCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Imprimir)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(427, 427, 427))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNombreEmpresa)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Imprimir)
                            .addComponent(btnSalir))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(836, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        if (this.tipoUsuario.getText().trim() == "1") {
            indexHome boladito = new indexHome();
            boladito.setVisible(true);
            boladito.jmLibroDiario.setVisible(false);
            boladito.jmCierres.setVisible(false);
            boladito.jmAsientos.setVisible(false);
            boladito.jmCrearCuenta.setVisible(false);
            boladito.jlLogueadoComo.setText("Logueado como Usuario sin credencial");
            boladito.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
            this.hide();
            System.out.println("WUUJUUU!!!");
        } else {
            new indexHome().setVisible(true);
            indexHome.jlLogueadoComo.setText("Logueado como Administrador");
            indexHome.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
            this.hide();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        // TODO add your handling code here:
        try {
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setPrintable(this);
            job.printDialog();
            job.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PrinterName.class.getName()).log(Level.SEVERE, "prueba", ex);
        }
    }//GEN-LAST:event_ImprimirActionPerformed

    private void btnEsDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsDefectoActionPerformed
        jPEsDefecto.setVisible(true);
        jPinicioER.setVisible(false);
    }//GEN-LAST:event_btnEsDefectoActionPerformed

    private void btnMModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMModificarActionPerformed
         if (txtMCuenta.getText().trim().isEmpty() || txtMIdPadre.getText().trim().isEmpty() || txtMSaldo.getText().trim().isEmpty() || lblMCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No ha ingresado todos los valores", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
             int id_catalogo = Integer.parseInt(idCatalogo.getText());

            int id_cuenta = Integer.parseInt(lblMCodigo.getText());
            int id_padre = Integer.parseInt(txtMIdPadre.getText());
            double valor = Double.parseDouble(txtMSaldo.getText());
            String tipo = "Deudor";
            int tipo_saldo;

            if (tipo.equals(cmbMTipo.getSelectedItem())) {
                tipo_saldo = 0;
            } else {
                tipo_saldo = 1;
            }

            int idcatalogo = Integer.parseInt(idCatalogo.getText().trim());

            Cuenta cuen = new Cuenta(id_cuenta, txtMCuenta.getText(), valor, id_padre, idcatalogo, tipo_saldo);
            try{
                opModificar.UpdaCuenta(cuen);
            }catch(Exception ex){
                System.out.println("Problemas al modificar la cuenta "+ex);
            }
            
            limpiarModificar();
            DefaultTableModel model = new DefaultTableModel();
            jTModificar.setModel(model);
            op.allCuentas(jTModificar, id_catalogo);
            
        }
    }//GEN-LAST:event_btnMModificarActionPerformed

    private void jTModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTModificarMouseClicked
        int fila = jTModificar.getSelectedRow();
        System.out.println("Fila " + fila);
     
                

        try {
            lblMCodigo.setText(jTModificar.getValueAt(fila, 0).toString());
            txtMIdPadre.setText(jTModificar.getValueAt(fila, 1).toString());
            txtMCuenta.setText(jTModificar.getValueAt(fila, 2).toString());
            txtMSaldo.setText(jTModificar.getValueAt(fila, 3).toString().replace("$", ""));
            if (jTModificar.getValueAt(fila, 4).toString().equals("Deudor")) {
                cmbMTipo.setSelectedIndex(0);
            } else {
                cmbMTipo.setSelectedIndex(1);
            }

        } catch (Exception ex) {
            System.out.println("Error " + ex);

        }
        txtMSaldo.requestFocus();
    }//GEN-LAST:event_jTModificarMouseClicked

    private void btnMCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCancelarActionPerformed
        limpiarModificar();
        cmbMTipo.setSelectedIndex(0);
        txtMCuenta.requestFocus();
    }//GEN-LAST:event_btnMCancelarActionPerformed

    public void limpiarModificar(){
            lblMCodigo.setText("");
            txtMIdPadre.setText("");
            txtMCuenta.setText("");
            txtMSaldo.setText("");
    }
    public void mostrarEstadosFinancieros() {
        // Mostrar todos los estados Financieros:
        int id_catalogo = Integer.parseInt(idCatalogo.getText());

        op.IngresosEstadoResultado(jtIngresosEstadoResultado, id_catalogo);
        op.GastosEstadoResultado(jtGastosEstadoResultados, id_catalogo);

        jlTotalIngresos.setText("$" + String.valueOf(op.getTotalIngresos()));
        jlTotalGastos.setText("$" + String.valueOf(op.getTotalGastos()));
        BigDecimal utilidad = new BigDecimal(String.valueOf(op.getTotalIngresos() - op.getTotalGastos()));

        utilidad = utilidad.setScale(2, RoundingMode.HALF_UP);
        jlUtilidadEstadoResultado.setText("$" + utilidad);
        jlUtilidad.setText("$" + utilidad);

        double valors = 0;
        double u = op.getTotalIngresos();
    
        for(int i=0;i<jtIngresosEstadoResultado.getRowCount();i++){
        valors = ((Double.parseDouble(jtIngresosEstadoResultado.getModel().getValueAt(i, 1).toString())*100)/u);
        jtIngresosEstadoResultado.getModel().setValueAt((df.format(valors)+"%"),i ,2);
        }
        
        for(int i=0;i<jtGastosEstadoResultados.getRowCount();i++){
        valors = ((Double.parseDouble(jtGastosEstadoResultados.getModel().getValueAt(i, 1).toString())*100)/u);
        jtGastosEstadoResultados.getModel().setValueAt((df.format(valors)+"%"),i ,2);
        }
         
        lblIngresosAV.setText(df.format((op.getTotalIngresos()*100)/u)+"%");
        lblGastosAV.setText(df.format((op.getTotalGastos()*100)/u)+"%");
        lblUtilidadAV.setText(df.format((utilidad.doubleValue()*100)/u)+"%");
        
        
        op.VariacionCapital(jtCapitalesEstadoResultado, id_catalogo);
        op.variacionCapitalRetiros(jtRetiros, id_catalogo);

        BigDecimal saldoRetiros = new BigDecimal(String.valueOf(op.getTotalRetiros()));
        jlTotalRetiros.setText("$" + saldoRetiros);
        BigDecimal saldoCapital = new BigDecimal(String.valueOf(op.getSaldoCapital()));
        BigDecimal capital = utilidad.add(saldoCapital).subtract(saldoRetiros);

        capital = capital.setScale(2, RoundingMode.HALF_UP);
        jlTotalCapital.setText("$" + capital);

        //Para el BG
        op.balanceGeneralActivosCorrientes(jtActivosCorrientesBG, id_catalogo);
        BigDecimal saldoActivosCorrientesBG = new BigDecimal(String.valueOf(op.getSaldoActivosCorrientes()));
        saldoActivosCorrientesBG = saldoActivosCorrientesBG.setScale(2, RoundingMode.HALF_UP);
        lblTotalActivosCorrientesBG.setText("$" + saldoActivosCorrientesBG);

        op.balanceGeneralActivosFijos(jtActivosFijosBG, id_catalogo);
        BigDecimal saldoActivosFijosBG = new BigDecimal(String.valueOf(op.getSaldoActivosFijos()));
        saldoActivosFijosBG = saldoActivosFijosBG.setScale(2, RoundingMode.HALF_UP);
        lblTotalActivosFijosBG.setText("$" + saldoActivosFijosBG);

        lblTotalActivosBG.setText("$" + (saldoActivosCorrientesBG.doubleValue() + saldoActivosFijosBG.doubleValue()));

        op.balanceGeneralPasivosCorrientes(jtPasivosCorrientesBG, id_catalogo);
        BigDecimal saldoPasivosCorrientesBG = new BigDecimal(String.valueOf(op.getSaldoPasivosCorrientes()));
        saldoPasivosCorrientesBG = saldoPasivosCorrientesBG.setScale(2, RoundingMode.HALF_UP);
        lblTotalPasivosCorrientesBG.setText("$" + saldoPasivosCorrientesBG);
        capital = capital.add(saldoPasivosCorrientesBG);

        op.balanceGeneralPasivosFijos(jtPasivosFijosBG, id_catalogo);
        BigDecimal saldoPasivosFijosBG = new BigDecimal(String.valueOf(op.getSaldoPasivosFijos()));
        saldoPasivosFijosBG = saldoPasivosFijosBG.setScale(2, RoundingMode.HALF_UP);
        lblTotalPasivosFijosBG.setText("$" + saldoPasivosFijosBG);
        capital = capital.add(saldoPasivosFijosBG);

        lblTotalPasivosBG.setText("$" + (saldoPasivosCorrientesBG.doubleValue() + saldoPasivosFijosBG.doubleValue()));

        
        op.balanceGeneralCapital(jtCapitalContableBG, id_catalogo);
        BigDecimal saldoCapitalContableBG = new BigDecimal(String.valueOf(op.getSaldoCapitalAV()));
        saldoCapitalContableBG = saldoCapitalContableBG.setScale(2, RoundingMode.HALF_UP);
        lblTotalCapitalBG.setText("$" + saldoCapitalContableBG);
        capital = capital.add(saldoCapitalContableBG);
        
//---------------------------------

        
        //Analsis vertical
        double p = saldoActivosCorrientesBG.doubleValue() + saldoActivosFijosBG.doubleValue();
              
                
        lblTotalActivosAV.setText("100%");
        lblPasivoCapitalAV.setText("100%");
        lblActivosCorrientesAV.setText(df.format((saldoActivosCorrientesBG.doubleValue()*100)/p)+"%");
        lblActivosFijosAV.setText(df.format((saldoActivosFijosBG.doubleValue()*100)/p)+"%");
        lblPasivosCorrientesAV.setText(df.format((saldoPasivosCorrientesBG.doubleValue()*100)/p)+"%");
        lblPasivosFijosAV.setText(df.format((saldoPasivosFijosBG.doubleValue()*100)/p)+"%");
        lblCapitalContableAV.setText(df.format((saldoCapitalContableBG.doubleValue()*100)/p)+"%");
        double valor = 0;
               
        for(int i=0;i<jtActivosCorrientesBG.getRowCount();i++){
        valor = ((Double.parseDouble(jtActivosCorrientesBG.getModel().getValueAt(i, 1).toString())*100)/p);
        jtActivosCorrientesBG.getModel().setValueAt((df.format(valor)+"%"),i ,2);
        }
        
               
        for(int i=0;i<jtActivosFijosBG.getRowCount();i++){
        valor = ((Double.parseDouble(jtActivosFijosBG.getModel().getValueAt(i, 1).toString())*100)/p);
        jtActivosFijosBG.getModel().setValueAt((df.format(valor)+"%"),i ,2);
        }
        
        for(int i=0;i<jtPasivosCorrientesBG.getRowCount();i++){
        valor = ((Double.parseDouble(jtPasivosCorrientesBG.getModel().getValueAt(i, 1).toString())*100)/p);
        jtPasivosCorrientesBG.getModel().setValueAt((df.format(valor)+"%"),i ,2);
        }
        
        for(int i=0;i<jtPasivosFijosBG.getRowCount();i++){
        valor = ((Double.parseDouble(jtPasivosFijosBG.getModel().getValueAt(i, 1).toString())*100)/p);
        jtPasivosFijosBG.getModel().setValueAt((df.format(valor)+"%"),i ,2);
        }
        
        for(int i=0;i<jtCapitalContableBG.getRowCount();i++){
        valor = ((Double.parseDouble(jtCapitalContableBG.getModel().getValueAt(i, 1).toString())*100)/p);
        jtCapitalContableBG.getModel().setValueAt((df.format(valor)+"%"),i ,2);
        }
        
//      lblPasivosCorrientesAV.setText("%"+());

        capital = capital.setScale(2, RoundingMode.HALF_UP);
        lblPasivoCapital.setText("$" + (saldoPasivosCorrientesBG.doubleValue()+saldoPasivosFijosBG.doubleValue()+saldoCapitalContableBG.doubleValue()));
        //--------------------------------------
        //Modificar Cuentas
        op.allCuentas(jTModificar, id_catalogo);


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceGeneral().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Imprimir;
    private javax.swing.JButton btnEsDefecto;
    private javax.swing.JButton btnEsPersonalizado;
    private javax.swing.JButton btnMCancelar;
    private javax.swing.JButton btnMModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbMTipo;
    public static final javax.swing.JLabel idCatalogo = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPEsDefecto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPinicioER;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTModificar;
    private javax.swing.JTabbedPane jTabbedPane5;
    public static final javax.swing.JLabel jlNombreEmpresa = new javax.swing.JLabel();
    private javax.swing.JLabel jlTotalCapital;
    private javax.swing.JLabel jlTotalGastos;
    private javax.swing.JLabel jlTotalIngresos;
    private javax.swing.JLabel jlTotalRetiros;
    private javax.swing.JLabel jlUtilidad;
    private javax.swing.JLabel jlUtilidadEstadoResultado;
    private javax.swing.JTable jtActivosCorrientesBG;
    private javax.swing.JTable jtActivosFijosBG;
    private javax.swing.JTable jtCapitalContableBG;
    private javax.swing.JTable jtCapitalesEstadoResultado;
    private javax.swing.JTable jtGastosEstadoResultados;
    private javax.swing.JTable jtIngresosEstadoResultado;
    private javax.swing.JTable jtPasivosCorrientesBG;
    private javax.swing.JTable jtPasivosFijosBG;
    private javax.swing.JTable jtRetiros;
    private javax.swing.JLabel lblActivosCorrientesAV;
    private javax.swing.JLabel lblActivosCorrientesAV1;
    private javax.swing.JLabel lblActivosFijosAV;
    private javax.swing.JLabel lblCapitalContableAV;
    private javax.swing.JLabel lblGastosAV;
    private javax.swing.JLabel lblIngresosAV;
    private javax.swing.JLabel lblMCodigo;
    private javax.swing.JLabel lblPasivoCapital;
    private javax.swing.JLabel lblPasivoCapitalAV;
    private javax.swing.JLabel lblPasivosCorrientesAV;
    private javax.swing.JLabel lblPasivosFijosAV;
    private javax.swing.JLabel lblTotalActivosAV;
    private javax.swing.JLabel lblTotalActivosBG;
    private javax.swing.JLabel lblTotalActivosCorrientesBG;
    private javax.swing.JLabel lblTotalActivosFijosBG;
    private javax.swing.JLabel lblTotalCapitalBG;
    private javax.swing.JLabel lblTotalPasivosAV;
    private javax.swing.JLabel lblTotalPasivosBG;
    private javax.swing.JLabel lblTotalPasivosCorrientesBG;
    private javax.swing.JLabel lblTotalPasivosFijosBG;
    private javax.swing.JLabel lblUtilidadAV;
    public static final javax.swing.JLabel tipoUsuario = new javax.swing.JLabel();
    private javax.swing.JTextField txtMCuenta;
    private javax.swing.JTextField txtMIdPadre;
    private javax.swing.JTextField txtMSaldo;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex > 0) {
            /* We have only one page, and 'page' is zero-based */
            return NO_SUCH_PAGE;
        }

        Graphics2D g2d = (Graphics2D) graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

        jPanel3.printAll(graphics);

        return PAGE_EXISTS;

    }
}
