/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Operaciones.Operaciones;
import Operaciones.OperacionesCierres;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class indexHome extends javax.swing.JFrame {

    logeo tito = new logeo();
    
    public int idCatalogo;
    Operaciones tablo = new Operaciones();
    OperacionesCierres melvin = new OperacionesCierres();
    /**
     * Creates new form indexHome
     */
    public indexHome() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/house.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")   /*
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmLibroDiario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmEstadosFinancieros = new javax.swing.JMenu();
        jmBalanzaComprobacion = new javax.swing.JMenu();
        jmAsientos = new javax.swing.JMenu();
        jmTablaAjustes = new javax.swing.JMenuItem();
        jmCierres = new javax.swing.JMenu();
        jmCierresContables = new javax.swing.JMenuItem();
        jmCierresAntiguos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmRatiosFinancieros = new javax.swing.JMenuItem();
        jmCrearCuenta = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmCrearCuentaNueva = new javax.swing.JMenuItem();
        jmEliminarCuenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmCrearEmpresa = new javax.swing.JMenuItem();
        jmEliminarEmpresa = new javax.swing.JMenuItem();
        jmCrearUsuario = new javax.swing.JMenuItem();
        jmEliminarUsuario = new javax.swing.JMenuItem();
        jmAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Yome - Financial System - v.3.012");
        setMinimumSize(new java.awt.Dimension(946, 360));
        setResizable(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/door_out.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        idCatalogoGlobal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idCatalogoGlobal.setForeground(new java.awt.Color(240, 240, 240));

        jLabel1.setBackground(new java.awt.Color(0, 210, 40));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/binmoney.jpg"))); // NOI18N

        tipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tipoUsuario.setForeground(new java.awt.Color(240, 240, 240));

        jlLogueadoComo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jlLogueadoComo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jlNombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        nombreUsuario.setForeground(new java.awt.Color(240, 240, 240));

        jmLibroDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book.png"))); // NOI18N
        jmLibroDiario.setText("Libro Diario");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_open.png"))); // NOI18N
        jMenuItem1.setText("Asientos Diarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmLibroDiario.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report.png"))); // NOI18N
        jMenuItem2.setText("Libro Mayor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmLibroDiario.add(jMenuItem2);

        jMenuBar1.add(jmLibroDiario);

        jmEstadosFinancieros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coins.png"))); // NOI18N
        jmEstadosFinancieros.setText("Estados financieros");
        jmEstadosFinancieros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmEstadosFinancierosMouseClicked(evt);
            }
        });
        jmEstadosFinancieros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEstadosFinancierosActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmEstadosFinancieros);

        jmBalanzaComprobacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table.png"))); // NOI18N
        jmBalanzaComprobacion.setText("Balanza de Comprobacion");
        jmBalanzaComprobacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmBalanzaComprobacionMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmBalanzaComprobacion);

        jmAsientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wrench.png"))); // NOI18N
        jmAsientos.setText("Ajustes");

        jmTablaAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wrench_orange.png"))); // NOI18N
        jmTablaAjustes.setText("Tabla de Ajustes");
        jmTablaAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTablaAjustesActionPerformed(evt);
            }
        });
        jmAsientos.add(jmTablaAjustes);

        jMenuBar1.add(jmAsientos);

        jmCierres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator.png"))); // NOI18N
        jmCierres.setText("Cierres");

        jmCierresContables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lightning.png"))); // NOI18N
        jmCierresContables.setText("Cierre Contable");
        jmCierresContables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCierresContablesActionPerformed(evt);
            }
        });
        jmCierres.add(jmCierresContables);

        jmCierresAntiguos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clock.png"))); // NOI18N
        jmCierresAntiguos.setText("Cierres Antiguos");
        jmCierresAntiguos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCierresAntiguosActionPerformed(evt);
            }
        });
        jmCierres.add(jmCierresAntiguos);

        jMenuBar1.add(jmCierres);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart_line.png"))); // NOI18N
        jMenu1.setText("Analisis Financieros");

        jmRatiosFinancieros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart_bar.png"))); // NOI18N
        jmRatiosFinancieros.setText("Ratios Financieros");
        jmRatiosFinancieros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRatiosFinancierosActionPerformed(evt);
            }
        });
        jMenu1.add(jmRatiosFinancieros);

        jMenuBar1.add(jMenu1);

        jmCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_suit.png"))); // NOI18N
        jmCrearCuenta.setText("Opciones");

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_open.png"))); // NOI18N
        jMenu2.setText("Manejo Cuentas");

        jmCrearCuentaNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jmCrearCuentaNueva.setText("Crear Cuenta");
        jmCrearCuentaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearCuentaNuevaActionPerformed(evt);
            }
        });
        jMenu2.add(jmCrearCuentaNueva);

        jmEliminarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        jmEliminarCuenta.setText("Eliminar Cuenta");
        jmEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarCuentaActionPerformed(evt);
            }
        });
        jMenu2.add(jmEliminarCuenta);

        jmCrearCuenta.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_gray.png"))); // NOI18N
        jMenu3.setText("Manejo Empresarial");

        jmCrearEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house.png"))); // NOI18N
        jmCrearEmpresa.setText("Crear Empresa");
        jmCrearEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearEmpresaActionPerformed(evt);
            }
        });
        jMenu3.add(jmCrearEmpresa);

        jmEliminarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house_link.png"))); // NOI18N
        jmEliminarEmpresa.setText("Eliminar Empresa");
        jmEliminarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarEmpresaActionPerformed(evt);
            }
        });
        jMenu3.add(jmEliminarEmpresa);

        jmCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_add.png"))); // NOI18N
        jmCrearUsuario.setText("Crear Usuario");
        jmCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(jmCrearUsuario);

        jmEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_delete.png"))); // NOI18N
        jmEliminarUsuario.setText("Eliminar Usuario");
        jmEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(jmEliminarUsuario);

        jmCrearCuenta.add(jMenu3);

        jMenuBar1.add(jmCrearCuenta);

        jmAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_addresses.png"))); // NOI18N
        jmAcercaDe.setText("Acerca de");
        jmAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAcercaDeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogueadoComo, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCatalogoGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tipoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idCatalogoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlLogueadoComo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(973, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
*/
//Fin del InitComponets antiguo
    
 private void initComponents(){    //Init nuevo
 
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();        
        jMenuBar1 = new javax.swing.JMenuBar();
        jmLibroDiario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();     
        jMenuItem2 = new javax.swing.JMenuItem();
        jmEstadosFinancieros = new javax.swing.JMenu();
        jmBalanzaComprobacion = new javax.swing.JMenu();
        jmAsientos = new javax.swing.JMenu();
        jmTablaAjustes = new javax.swing.JMenuItem();
        jmCierres = new javax.swing.JMenu();
        jmCierresContables = new javax.swing.JMenuItem();
        jmCierresAntiguos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmRatiosFinancieros = new javax.swing.JMenuItem();
        jmCrearCuenta = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jmCrearCuentaNueva = new javax.swing.JMenuItem();
        jmEliminarCuenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmCrearEmpresa = new javax.swing.JMenuItem();
        jmEliminarEmpresa = new javax.swing.JMenuItem();
        jmCrearUsuario = new javax.swing.JMenuItem();
        jmEliminarUsuario = new javax.swing.JMenuItem();
        jmAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SISTEMAS & SISTEMAS");
        setResizable(false);
        setUndecorated(true);
        

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/door_out.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
setSize(new java.awt.Dimension(1000, 350));
        idCatalogoGlobal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idCatalogoGlobal.setForeground(new java.awt.Color(240, 240, 240));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/binmoney.jpg"))); // NOI18N

        tipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tipoUsuario.setForeground(new java.awt.Color(240, 240, 240));

        jlLogueadoComo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jlLogueadoComo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jlNombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlNombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        nombreUsuario.setForeground(new java.awt.Color(240, 240, 240));

        jmLibroDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book.png"))); // NOI18N
        jmLibroDiario.setText("Libro Diario");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_open.png"))); // NOI18N
        jMenuItem1.setText("Asientos Diarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmLibroDiario.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report.png"))); // NOI18N
        jMenuItem2.setText("Libro Mayor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmLibroDiario.add(jMenuItem2);

        jMenuBar1.add(jmLibroDiario);

        jmEstadosFinancieros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coins.png"))); // NOI18N
        jmEstadosFinancieros.setText("Estados financieros");
        jmEstadosFinancieros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmEstadosFinancierosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmEstadosFinancieros);

        jmBalanzaComprobacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/table.png"))); // NOI18N
        jmBalanzaComprobacion.setText("Balanza de Comprobacion");
        jmBalanzaComprobacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmBalanzaComprobacionMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmBalanzaComprobacion);

        jmAsientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wrench.png"))); // NOI18N
        jmAsientos.setText("Ajustes");

        jmTablaAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/wrench_orange.png"))); // NOI18N
        jmTablaAjustes.setText("Tabla de Ajustes");
        jmTablaAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTablaAjustesActionPerformed(evt);
            }
        });
        jmAsientos.add(jmTablaAjustes);

        jMenuBar1.add(jmAsientos);

        jmCierres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calculator.png"))); // NOI18N
        jmCierres.setText("Cierres");

        jmCierresContables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lightning.png"))); // NOI18N
        jmCierresContables.setText("Cierre Contable");
        jmCierresContables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCierresContablesActionPerformed(evt);
            }
        });
        jmCierres.add(jmCierresContables);

        jmCierresAntiguos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clock.png"))); // NOI18N
        jmCierresAntiguos.setText("Cierres Antiguos");
        jmCierresAntiguos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCierresAntiguosActionPerformed(evt);
            }
        });
        jmCierres.add(jmCierresAntiguos);

        jMenuBar1.add(jmCierres);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart_line.png"))); // NOI18N
        jMenu1.setText("Analisis Financieros");

        jmRatiosFinancieros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chart_bar.png"))); // NOI18N
        jmRatiosFinancieros.setText("Ratios Financieros");
        jmRatiosFinancieros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRatiosFinancierosActionPerformed(evt);
            }
        });
        jMenu1.add(jmRatiosFinancieros);

        jMenuBar1.add(jMenu1);

        jmCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_suit.png"))); // NOI18N
        jmCrearCuenta.setText("Opciones");

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_open.png"))); // NOI18N
        jMenu2.setText("Manejo Cuentas");

        jmCrearCuentaNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jmCrearCuentaNueva.setText("Crear Cuenta");
        jmCrearCuentaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearCuentaNuevaActionPerformed(evt);
            }
        });
        jMenu2.add(jmCrearCuentaNueva);

        jmEliminarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        jmEliminarCuenta.setText("Eliminar Cuenta");
        jmEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarCuentaActionPerformed(evt);
            }
        });
        jMenu2.add(jmEliminarCuenta);

        jmCrearCuenta.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_gray.png"))); // NOI18N
        jMenu3.setText("Manejo Empresarial");

        jmCrearEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house.png"))); // NOI18N
        jmCrearEmpresa.setText("Crear Empresa");
        jmCrearEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearEmpresaActionPerformed(evt);
            }
        });
        jMenu3.add(jmCrearEmpresa);

        jmEliminarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house_link.png"))); // NOI18N
        jmEliminarEmpresa.setText("Eliminar Empresa");
        jmEliminarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarEmpresaActionPerformed(evt);
            }
        });
        jMenu3.add(jmEliminarEmpresa);

        jmCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_add.png"))); // NOI18N
        jmCrearUsuario.setText("Crear Usuario");
        jmCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(jmCrearUsuario);

        jmEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_delete.png"))); // NOI18N
        jmEliminarUsuario.setText("Eliminar Usuario");
        jmEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(jmEliminarUsuario);

        jmCrearCuenta.add(jMenu3);

        jMenuBar1.add(jmCrearCuenta);

        jmAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_addresses.png"))); // NOI18N
        jmAcercaDe.setText("Acerca de");
        jmAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAcercaDeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogueadoComo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idCatalogoGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tipoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idCatalogoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlLogueadoComo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1100, 330));
        setLocationRelativeTo(null);
 }   //fin init nuevo
 
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere salir del sistema?", "Confirmanción", JOptionPane.YES_NO_OPTION) == 1) {
        } else {
            new logeo().setVisible(true);
            this.hide();
        }
    }                 

    private void jmRatiosFinancierosActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // Ratios financieros:
        RatiosForm yome = new RatiosForm();
        yome.setVisible(true);
        yome.idCatalogo.setText(this.idCatalogoGlobal.getText());
        yome.tipoUsuario.setText(this.tipoUsuario.getText());
        yome.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        yome.realizarTito();
        yome.mostrarRatios();
        this.hide();
        
    }                                                   

    private void jmEstadosFinancierosMouseClicked(java.awt.event.MouseEvent evt) {                                                  
        // Menu Estados Financieros:
        BalanceGeneral Joss = new BalanceGeneral();
        Joss.setVisible(true);
        Joss.idCatalogo.setText(this.idCatalogoGlobal.getText());
        Joss.tipoUsuario.setText(this.tipoUsuario.getText());
        Joss.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        
        Joss.mostrarEstadosFinancieros();
        
        this.hide();
    }                                                 

    private void jmBalanzaComprobacionMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        // Menu Balanza de Comprobacion
        
        BalanceComprobacion kmote = new BalanceComprobacion();
        kmote.setVisible(true);
        kmote.idCatalogo.setText(this.idCatalogoGlobal.getText());
        kmote.tipoUsuario.setText(this.tipoUsuario.getText());
        kmote.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        kmote.cargarBalanceComprobacion();
        
        this.hide();
    }                                                  

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // Menu Libro Diario
        
        Asientos tablo = new Asientos();

        tablo.setVisible(true);
        tablo.idCatalogo.setText(this.idCatalogoGlobal.getText());
        tablo.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        
        tablo.listarCuentas();
        
        this.hide();
    }                                          

    private void jmTablaAjustesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        Ajustes tito = new Ajustes();
        
        tito.setVisible(true);
        tito.idCatalogo.setText(this.idCatalogoGlobal.getText());
        tito.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        
        tito.listarCuentas();
        
        this.hide();
    }                                              

    private void jmCierresContablesActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // Cierres...:
        cierreContable ayala = new cierreContable();
        
        ayala.setVisible(true);
        ayala.idCatalogo.setText(this.idCatalogoGlobal.getText());
        ayala.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        ayala.mostrarTodo();
        
        
        this.hide();
    }                                                  

    
    //Botones copia:(
    /*
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere salir del sistema?", "Confirmanción", JOptionPane.YES_NO_OPTION) == 1) {
        } else {
            new logeo().setVisible(true);
            this.hide();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmRatiosFinancierosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRatiosFinancierosActionPerformed
        // Ratios financieros:
        RatiosForm yome = new RatiosForm();
        yome.setVisible(true);
        yome.idCatalogo.setText(this.idCatalogoGlobal.getText());
        yome.tipoUsuario.setText(this.tipoUsuario.getText());
        yome.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        yome.realizarTito();
        yome.mostrarRatios();
        this.hide();
        
    }//GEN-LAST:event_jmRatiosFinancierosActionPerformed

    private void jmEstadosFinancierosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmEstadosFinancierosMouseClicked
        // Menu Estados Financieros:
        BalanceGeneral Joss = new BalanceGeneral();
        Joss.setVisible(true);
        Joss.idCatalogo.setText(this.idCatalogoGlobal.getText());
        Joss.tipoUsuario.setText(this.tipoUsuario.getText());
        Joss.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        
        Joss.mostrarEstadosFinancieros();
        
        this.hide();
    }//GEN-LAST:event_jmEstadosFinancierosMouseClicked

    private void jmBalanzaComprobacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmBalanzaComprobacionMouseClicked
        // Menu Balanza de Comprobacion
        
        BalanceComprobacion kmote = new BalanceComprobacion();
        kmote.setVisible(true);
        kmote.idCatalogo.setText(this.idCatalogoGlobal.getText());
        kmote.tipoUsuario.setText(this.tipoUsuario.getText());
        kmote.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        kmote.cargarBalanceComprobacion();
        
        this.hide();
    }//GEN-LAST:event_jmBalanzaComprobacionMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Menu Libro Diario
        
        Asientos tablo = new Asientos();

        tablo.setVisible(true);
        tablo.idCatalogo.setText(this.idCatalogoGlobal.getText());
        tablo.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        
        tablo.listarCuentas();
        
        this.hide();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmTablaAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTablaAjustesActionPerformed
        // TODO add your handling code here:
        Ajustes tito = new Ajustes();
        
        tito.setVisible(true);
        tito.idCatalogo.setText(this.idCatalogoGlobal.getText());
        tito.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        
        tito.listarCuentas();
        
        this.hide();
    }//GEN-LAST:event_jmTablaAjustesActionPerformed

    private void jmCierresContablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCierresContablesActionPerformed
        // Cierres...:
        cierreContable ayala = new cierreContable();
        
        ayala.setVisible(true);
        ayala.idCatalogo.setText(this.idCatalogoGlobal.getText());
        ayala.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        ayala.mostrarTodo();
        
        
        this.hide();
    }//GEN-LAST:event_jmCierresContablesActionPerformed

    
    */
    private void jmAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAcercaDeMouseClicked
        // ACerca deee...
        AcercaDe Joss = new AcercaDe();
        Joss.setVisible(true);
        Joss.jlNombreEmpresa = this.jlNombreEmpresa.getText().trim();
        Joss.tipoUsuario = Integer.parseInt(this.tipoUsuario.getText().trim());
        this.hide();
    }//GEN-LAST:event_jmAcercaDeMouseClicked

    private void jmCrearCuentaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearCuentaNuevaActionPerformed
        // Crear Cuenta...:
        crearCuenta chepito = new crearCuenta();
        
        chepito.setVisible(true);
        chepito.idCatalogo.setText(this.idCatalogoGlobal.getText());
        chepito.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        
        this.hide();
    }//GEN-LAST:event_jmCrearCuentaNuevaActionPerformed

    private void jmEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEliminarCuentaActionPerformed
        // Eliminar Cuenta :(...:
        EliminarCuenta tumblimbi = new EliminarCuenta();
        
        tumblimbi.setVisible(true);
        tumblimbi.idCatalogo.setText(this.idCatalogoGlobal.getText());
        tumblimbi.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        
        tablo.listarCatalogo(tumblimbi.tablita, Integer.parseInt(idCatalogoGlobal.getText().trim()));
        
        this.hide();
    }//GEN-LAST:event_jmEliminarCuentaActionPerformed

    private void jmCrearEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearEmpresaActionPerformed
        // Crear Empresa...:
        CrearEmpresa chiltota = new CrearEmpresa();
        
        chiltota.setVisible(true);
        chiltota.jlNombreEmpresa = this.jlNombreEmpresa.getText().trim();
        chiltota.tipoUsuario = Integer.parseInt(this.tipoUsuario.getText().trim());
        this.hide();
    }//GEN-LAST:event_jmCrearEmpresaActionPerformed

    private void jmCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearUsuarioActionPerformed
       
        CrearUsuario ayala = new CrearUsuario();
        
        ayala.setVisible(true);
        ayala.jlNombreEmpresa = this.jlNombreEmpresa.getText().trim();
        ayala.tipoUsuario = Integer.parseInt(this.tipoUsuario.getText().trim());
        this.hide();
    }//GEN-LAST:event_jmCrearUsuarioActionPerformed

    private void jmEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEliminarUsuarioActionPerformed
        // Eliminar Usuario...:
        EliminarUsuario tumblimbi = new EliminarUsuario();
        
        tumblimbi.setVisible(true);
        tumblimbi.nombreUsuario.setText(this.nombreUsuario.getText());
        
        
        tablo.listarUsuarios(tumblimbi.tablita, tumblimbi.nombreUsuario.getText());
        
        this.hide();
        
    }//GEN-LAST:event_jmEliminarUsuarioActionPerformed

    private void jmEliminarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEliminarEmpresaActionPerformed
        // Eliminar Empresa....
        // NO hubo tiempo....
        JOptionPane.showMessageDialog(null, "No disponible", "Error - 000129992:EF", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jmEliminarEmpresaActionPerformed

    private void jmCierresAntiguosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCierresAntiguosActionPerformed
        // Cierres Antiguos menu...:
        cierresAntiguos tumblimbi = new cierresAntiguos();
        
        tumblimbi.setVisible(true);
        tumblimbi.idCatalogo.setText(this.idCatalogoGlobal.getText());
        tumblimbi.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        tumblimbi.tipoUsuario = Integer.parseInt(this.tipoUsuario.getText().trim());
        
         melvin.listarCierres(tumblimbi.tablita, Integer.parseInt(idCatalogoGlobal.getText().trim()));
        
        this.hide();
        
        
    }//GEN-LAST:event_jmCierresAntiguosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         Mayor tablo = new Mayor();

        tablo.setVisible(true);
        tablo.idCatalogo.setText(this.idCatalogoGlobal.getText());
        tablo.jlNombreEmpresa.setText(this.jlNombreEmpresa.getText());
        
        tablo.listarCuentas();
        
        this.hide();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmEstadosFinancierosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEstadosFinancierosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmEstadosFinancierosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(indexHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(indexHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(indexHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(indexHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new indexHome().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel idCatalogoGlobal = new javax.swing.JLabel();
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public static final javax.swing.JLabel jlLogueadoComo = new javax.swing.JLabel();
    public static final javax.swing.JLabel jlNombreEmpresa = new javax.swing.JLabel();
    private javax.swing.JMenu jmAcercaDe;
    public static javax.swing.JMenu jmAsientos;
    private javax.swing.JMenu jmBalanzaComprobacion;
    public static javax.swing.JMenu jmCierres;
    private javax.swing.JMenuItem jmCierresAntiguos;
    private javax.swing.JMenuItem jmCierresContables;
    public static javax.swing.JMenu jmCrearCuenta;
    private javax.swing.JMenuItem jmCrearCuentaNueva;
    private javax.swing.JMenuItem jmCrearEmpresa;
    private javax.swing.JMenuItem jmCrearUsuario;
    private javax.swing.JMenuItem jmEliminarCuenta;
    private javax.swing.JMenuItem jmEliminarEmpresa;
    private javax.swing.JMenuItem jmEliminarUsuario;
    private javax.swing.JMenu jmEstadosFinancieros;
    public static javax.swing.JMenu jmLibroDiario;
    private javax.swing.JMenuItem jmRatiosFinancieros;
    private javax.swing.JMenuItem jmTablaAjustes;
    public static final javax.swing.JLabel nombreUsuario = new javax.swing.JLabel();
    public static final javax.swing.JLabel tipoUsuario = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}

